name: CI With React Application

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Workflow runs when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: node:16 # Use the official Node.js Docker image

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci # Faster, clean install of dependencies

      - name: Build Application
        run: npm run build

      - name: Serve Application
        run: |
          npm install -g serve
          serve -s build -l 5000
